# This is a basic workflow to help you get started with Actions

name: BuildResume.CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
      - run: npm install -g resume-cli
      - run: npm install jsonresume-theme-colophon
      - run: resume export index.html --theme colophon
      - uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
